### PR TITLE
Use GitHub Actions

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by kamilkisiela** [comment]
hmmm not yet available in this repo :(

**Comment by Urigo** [comment]
@kamilkisiela maybe I can ask for it somehow?

**Comment by kamilkisiela** [comment]
@Urigo you can try to sign up [here](https://github.com/features/actions) but it's not important, just wanted to check if you and sofa have it.

**Comment by Urigo** [comment]
@kamilkisiela available now!

**Pull request merged**
