### PR TITLE
[api] replace express router with custom routes

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/Urigo/SOFA/pull/643

In this diff I replaced express with routes functions which are run
one after another and check if they match.

Changed tests to check real request instead of router props.

Note: review with hidden whitespaces

### CODE REVIEW

**Comment by TrySound** [comment]
cc @ardatan

**Comment by ardatan** [comment]
@kamilkisiela What do you think?

**Comment by LRipi** [comment]
@TrySound Do you think is that possible to implement the issue #611 to change the return value in your PR?

**Comment by TrySound** [comment]
Not really related to my PR. Though, yeah, change statusCode is easy. But the question is on which condition.

**Comment by LRipi** [comment]
Any news about an implementation of this feature?

**Pull request closed without merging**
