### PR TITLE
[breaking] allow to specify custom path and response status

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/Urigo/SOFA/issues/611 https://github.com/Urigo/SOFA/issues/608 https://github.com/Urigo/SOFA/issues/576

In this diff I replaced `method` map with `routes` map which allows to override default method, path and response status.
Please check if this can solve your problems.

cc @LRipi @basselalaraaj

### CODE REVIEW

**Comment by LRipi** [comment]
Seems fine for me! 😄

**Comment by LRipi** [comment]
Any idea about a date of merge, @TrySound ?

**Comment by ardatan** [comment]
@LRipi You can use `0.10.3-alpha.0` until this gets merged!

**Comment by LRipi** [comment]
I just noticed that we can't make a JSON file with this route config.
Is that normal?

**Comment by LRipi** [comment]
Any news about a merge?

**Pull request merged**
