### PR TITLE
fix: change the default error response representation to JSON

### PR DESCRIPTION
**Pull request by izumin5210**
related #1175 

The document is as follows, but in fact it was in plain text.
So we changed it to return `JSON.stringify` by default.

### CODE REVIEW

**Comment by ardatan** [comment]
Thanks for the fix. Could you add a unit test to prevent future regressions?

**Comment by izumin5210** [comment]
thanks!

added a unit test  f5540b3 ✅

**Comment by izumin5210** [comment]
@ardatan can you review this PR?

**Comment by ardatan** [comment]
Thanks @izumin5210 !

**Pull request merged**
